const ALERT: string = 'ALERT';
const REFETCH_CHATS: string = 'REFETCH_CHATS';

const NEW_ATTACHMENT: string = 'NEW_ATTACHMENT';
const NEW_MESSAGE_ALERT: string = 'NEW_MESSAGE_ALERT';

const NEW_REQUEST: string = 'NEW_REQUEST';
const NEW_MESSAGE: string = 'NEW_MESSAGE';

const START_TYPING: string = 'START_TYPING';
const STOP_TYPING: string = 'STOP_TYPING';

const CHAT_JOINED: string = 'CHAT_JOINED';
const CHAT_LEAVED: string = 'CHAT_LEAVED';

const ONLINE_USERS: string = 'ONLINE_USERS';
const OFFLINE_USERS: string = 'OFFLINE_USERS';

const SEEN_MESSAGE: string = 'SEEN_MESSAGE';

const ADD_USER: string = 'ADD_USER';

export {
    ALERT,
    REFETCH_CHATS,
    NEW_ATTACHMENT,
    NEW_MESSAGE_ALERT,
    NEW_REQUEST,
    NEW_MESSAGE,
    START_TYPING,
    STOP_TYPING,
    CHAT_JOINED,
    CHAT_LEAVED,
    ONLINE_USERS,
    OFFLINE_USERS,
    SEEN_MESSAGE,
    ADD_USER,
};
